CREATE TABLE USUARIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    NOMBRES VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(20) NOT NULL,
    CONTRASEÑA VARCHAR(20) NOT NULL,
    CEDULA VARCHAR(20),
    TELEFONO VARCHAR(20),
    REMEMBER BOOLEAN,

    CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID) -- Primary Key
);

CREATE TABLE TELEFONO_ORG (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    TELEFONO VARCHAR(20) NOT NULL,

    CONSTRAINT ID_TELEFONO_ORG_PK PRIMARY KEY (ID)
);

CREATE TABLE DIRECCION_ORG (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    DIRECCION VARCHAR(300) NOT NULL,

    CONSTRAINT ID_DIRECCION_ORG_PK PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZACION (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    DIRECCION_ORG_ID INTEGER NOT NULL,   -- ADD THIS and change constraint FK name
    TELEFONO_ORG_ID INTEGER NOT NULL,   -- ADD THIS and change constraint FK name

    CONSTRAINT ID_ORGANIZACION_PK PRIMARY KEY (ID),
    CONSTRAINT ID_DIRECCION_ORG_FK FOREIGN KEY (DIRECCION_ORG_ID) REFERENCES DIRECCION_ORG (ID),
    CONSTRAINT ID_TELEFONO_ORG_FK FOREIGN KEY (TELEFONO_ORG_ID) REFERENCES TELEFONO_ORG (ID)
);

CREATE TABLE PRODUCTO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    RUTA_IMAGEN VARCHAR(400) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(400),
    CODIGO VARCHAR(400),
    CANTIDAD INTEGER,
    PRECIO DOUBLE,
    COSTO DOUBLE,
    ORGANIZACION_ID INTEGER NOT NULL, --ADD THIS and change constraint FK name

    CONSTRAINT ID_PRODUCTO_PK PRIMARY KEY (ID), -- Primary Key
    CONSTRAINT ID_ORGANIZACION_FK FOREIGN KEY (ORGANIZACION_ID) REFERENCES ORGANIZACION (ID)
);